# Generated by Django 2.2.13 on 2020-06-14 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_U_M_E_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 0, 18, 25, 982537, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
